'use server';
import { redirect } from 'next/navigation';
import { revalidatePath } from 'next/cache';
import bcrypt from 'bcryptjs';
import { prisma } from '@/lib/prisma';
import { requireUser } from '@/lib/auth';
import { toNumber, ym } from '@/lib/utils';
import { Prisma } from '@prisma/client';

async function userId(){const u=await requireUser(); if(!u) redirect('/login'); return u.id;}
async function assertOpen(uid:string,date:Date){const m=ym(date); const c=await prisma.monthlyClosing.findUnique({where:{userId_month:{userId:uid,month:m}}}); if(c) throw new Error(`Bulan ${m} sudah closing`);}
const defaultIncome=['Jual Mobil','Profit Mobil','Ngopseh','Fee Makelar','Komisi','Titip Jual','Gaji','Bonus','Investasi','Freelance','Lainnya'];
const defaultExpense=['Operasional','Makan','BBM','Servis Mobil','Pajak','Cicilan','Tagihan','Belanja','Marketing','Transfer Keluarga','Investasi','Lainnya'];
export async function createAdmin(fd:FormData){const count=await prisma.user.count(); if(count>0) redirect('/login'); const email=String(fd.get('email')); const password=String(fd.get('password')); const fullName=String(fd.get('fullName')||'Admin'); const user=await prisma.user.create({data:{email,fullName,passwordHash:await bcrypt.hash(password,10)}}); await createDefaultCategories(user.id); redirect('/login');}
export async function createDefaultCategories(uid:string){await prisma.category.createMany({data:[...defaultIncome.map(name=>({userId:uid,name,type:'INCOME' as const,icon:'TrendingUp',color:'emerald'})),...defaultExpense.map(name=>({userId:uid,name,type:'EXPENSE' as const,icon:'Receipt',color:'blue'}))],skipDuplicates:true});}
export async function completeSetup(fd:FormData){const uid=await userId(); await createDefaultCategories(uid); const account=String(fd.get('account')||'Kas Utama'); const balance=toNumber(fd.get('balance')); await prisma.account.create({data:{userId:uid,name:account,type:String(fd.get('accountType')||'BANK') as any,balance,initialBalance:balance,isPrimary:true}}); const debtName=String(fd.get('debtName')||''); if(debtName) await prisma.debt.create({data:{userId:uid,type:'DEBT',name:debtName,amount:toNumber(fd.get('debtAmount')),remainingAmount:toNumber(fd.get('debtAmount')),dueDate:fd.get('debtDue')?new Date(String(fd.get('debtDue'))):null,notes:String(fd.get('debtNotes')||'')}}); const recName=String(fd.get('recName')||''); if(recName) await prisma.debt.create({data:{userId:uid,type:'RECEIVABLE',name:recName,amount:toNumber(fd.get('recAmount')),remainingAmount:toNumber(fd.get('recAmount')),dueDate:fd.get('recDue')?new Date(String(fd.get('recDue'))):null,notes:String(fd.get('recNotes')||'')}}); const invCat=String(fd.get('invCat')||''); if(invCat) await prisma.investmentSnapshot.create({data:{userId:uid,category:invCat,month:ym(),balance:toNumber(fd.get('invBalance')),notes:String(fd.get('invNotes')||'')}}); const carName=String(fd.get('carName')||''); if(carName) await prisma.car.create({data:{userId:uid,name:carName,brand:String(fd.get('brand')||''),model:String(fd.get('model')||''),year:Number(fd.get('year')||0)||null,purchasePrice:toNumber(fd.get('purchasePrice')),estimatedSellPrice:toNumber(fd.get('estimatedSellPrice')),notes:String(fd.get('carNotes')||'')}}); await prisma.user.update({where:{id:uid},data:{setupCompleted:true}}); redirect('/dashboard');}
export async function addAccount(fd:FormData){const uid=await userId(); const initial=toNumber(fd.get('initialBalance')); if(fd.get('isPrimary')) await prisma.account.updateMany({where:{userId:uid},data:{isPrimary:false}}); await prisma.account.create({data:{userId:uid,name:String(fd.get('name')),type:String(fd.get('type')) as any,balance:initial,initialBalance:initial,color:String(fd.get('color')||'emerald'),icon:String(fd.get('icon')||'Wallet'),isPrimary:!!fd.get('isPrimary')}}); revalidatePath('/accounts');}
export async function deleteAccount(fd:FormData){const uid=await userId(); await prisma.account.delete({where:{id:String(fd.get('id')),userId:uid} as any}); revalidatePath('/accounts');}
export async function addCategory(fd:FormData){const uid=await userId(); await prisma.category.create({data:{userId:uid,name:String(fd.get('name')),type:String(fd.get('type')) as any,icon:String(fd.get('icon')||'Circle'),color:String(fd.get('color')||'emerald'),isActive:true}}); revalidatePath('/categories');}
export async function toggleCategory(fd:FormData){const uid=await userId(); const id=String(fd.get('id')); const cat=await prisma.category.findFirst({where:{id,userId:uid}}); if(cat) await prisma.category.update({where:{id},data:{isActive:!cat.isActive}}); revalidatePath('/categories');}
export async function addTransaction(fd:FormData){const uid=await userId(); const type=String(fd.get('type')) as any; const amount=toNumber(fd.get('amount')); const date=new Date(String(fd.get('date'))); await assertOpen(uid,date); const accountId=String(fd.get('accountId')); const transferTo=String(fd.get('transferToAccountId')||''); await prisma.$transaction(async tx=>{const t=await tx.transaction.create({data:{userId:uid,type,amount,date,description:String(fd.get('description')||''),accountId,categoryId:type==='TRANSFER'?null:(String(fd.get('categoryId')||'')||null),transferToAccountId:type==='TRANSFER'?transferTo:null}}); if(type==='INCOME') await tx.account.update({where:{id:accountId},data:{balance:{increment:amount}}}); if(type==='EXPENSE') await tx.account.update({where:{id:accountId},data:{balance:{decrement:amount}}}); if(type==='TRANSFER'){await tx.account.update({where:{id:accountId},data:{balance:{decrement:amount}}}); await tx.account.update({where:{id:transferTo},data:{balance:{increment:amount}}});} await tx.transactionAuditLog.create({data:{userId:uid,transactionId:t.id,action:'CREATE',newData:t as any}});}); revalidatePath('/transactions'); revalidatePath('/dashboard');}
export async function deleteTransaction(fd:FormData){const uid=await userId(); const id=String(fd.get('id')); const t=await prisma.transaction.findFirst({where:{id,userId:uid}}); if(!t)return; await assertOpen(uid,t.date); await prisma.$transaction(async tx=>{if(t.type==='INCOME') await tx.account.update({where:{id:t.accountId},data:{balance:{decrement:t.amount}}}); if(t.type==='EXPENSE') await tx.account.update({where:{id:t.accountId},data:{balance:{increment:t.amount}}}); if(t.type==='TRANSFER'&&t.transferToAccountId){await tx.account.update({where:{id:t.accountId},data:{balance:{increment:t.amount}}}); await tx.account.update({where:{id:t.transferToAccountId},data:{balance:{decrement:t.amount}}});} await tx.transactionAuditLog.create({data:{userId:uid,transactionId:id,action:'DELETE',oldData:t as any}}); await tx.transaction.delete({where:{id}});}); revalidatePath('/transactions'); revalidatePath('/dashboard');}
export async function addCar(fd:FormData){const uid=await userId(); const accountId=String(fd.get('accountId')||''); const purchase=toNumber(fd.get('purchasePrice')); const myMoney=toNumber(fd.get('myMoney')); const debtName=String(fd.get('debtName')||''); const debtAmount=toNumber(fd.get('debtAmount')); await prisma.$transaction(async tx=>{const car=await tx.car.create({data:{userId:uid,name:String(fd.get('name')),brand:String(fd.get('brand')||''),model:String(fd.get('model')||''),year:Number(fd.get('year')||0)||null,color:String(fd.get('color')||''),transmission:String(fd.get('transmission')||''),licensePlate:String(fd.get('licensePlate')||''),frameNumber:String(fd.get('frameNumber')||''),engineNumber:String(fd.get('engineNumber')||''),mileage:Number(fd.get('mileage')||0)||null,purchasePrice:purchase,estimatedSellPrice:toNumber(fd.get('estimatedSellPrice')),notes:String(fd.get('notes')||''),photos:String(fd.get('photos')||'').split('\n').filter(Boolean)}}); if(accountId&&myMoney>0){await tx.account.update({where:{id:accountId},data:{balance:{decrement:myMoney}}}); await tx.transaction.create({data:{userId:uid,accountId,type:'EXPENSE',amount:myMoney,date:new Date(),description:`Beli mobil ${car.name}`,sourceType:'car_purchase',sourceId:car.id}});} if(debtName&&debtAmount>0){await tx.debt.create({data:{userId:uid,type:'DEBT',name:debtName,amount:debtAmount,remainingAmount:debtAmount,carId:car.id,notes:`Pinjaman untuk beli mobil ${car.name}`}});}}); revalidatePath('/cars'); revalidatePath('/debts'); revalidatePath('/dashboard');}
export async function deleteCar(fd:FormData){const uid=await userId(); const id=String(fd.get('id')); await prisma.car.delete({where:{id,userId:uid} as any}); revalidatePath('/cars'); revalidatePath('/dashboard');}
export async function addCarCost(fd:FormData){const uid=await userId(); const amount=toNumber(fd.get('amount')); const accountId=String(fd.get('accountId')); const date=new Date(String(fd.get('date'))); await assertOpen(uid,date); await prisma.$transaction(async tx=>{const c=await tx.carCost.create({data:{userId:uid,carId:String(fd.get('carId')),accountId,amount,description:String(fd.get('description')),date}}); await tx.account.update({where:{id:accountId},data:{balance:{decrement:amount}}}); await tx.transaction.create({data:{userId:uid,accountId,type:'EXPENSE',amount,date,description:`Biaya mobil: ${c.description}`,sourceType:'car_cost',sourceId:c.id}});}); revalidatePath('/cars');}
export async function sellCar(fd:FormData){const uid=await userId(); const id=String(fd.get('carId')); const accountId=String(fd.get('accountId')); const price=toNumber(fd.get('sellPrice')); const date=new Date(String(fd.get('date'))); await assertOpen(uid,date); await prisma.$transaction(async tx=>{await tx.car.update({where:{id,userId:uid} as any,data:{status:'SOLD',sellPrice:price,soldAt:date}}); await tx.account.update({where:{id:accountId},data:{balance:{increment:price}}}); await tx.transaction.create({data:{userId:uid,accountId,type:'INCOME',amount:price,date,description:'Jual mobil',sourceType:'car_sale',sourceId:id}}); const carDebts=await tx.debt.findMany({where:{userId:uid,carId:id,status:'ACTIVE'}}); for(const debt of carDebts){const payAmount=Number(debt.remainingAmount); await tx.debtPayment.create({data:{userId:uid,debtId:debt.id,accountId,amount:payAmount,date,notes:`Auto-lunas dari penjualan mobil`}}); await tx.debt.update({where:{id:debt.id},data:{remainingAmount:0,status:'PAID'}}); await tx.account.update({where:{id:accountId},data:{balance:{decrement:payAmount}}}); await tx.transaction.create({data:{userId:uid,accountId,type:'EXPENSE',amount:payAmount,date,description:`Bayar hutang ${debt.name} (mobil laku)`,sourceType:'debt_payment',sourceId:debt.id}});}}); revalidatePath('/cars'); revalidatePath('/debts'); revalidatePath('/dashboard');}
export async function addDebt(fd:FormData){const uid=await userId(); const amount=toNumber(fd.get('amount')); const accountId=String(fd.get('accountId')||''); const type=String(fd.get('type')); await prisma.$transaction(async tx=>{await tx.debt.create({data:{userId:uid,type:type as any,name:String(fd.get('name')),amount,remainingAmount:amount,accountId:accountId||null,dueDate:fd.get('dueDate')?new Date(String(fd.get('dueDate'))):null,notes:String(fd.get('notes')||'')}}); if(accountId){if(type==='DEBT'){await tx.account.update({where:{id:accountId},data:{balance:{increment:amount}}});}else if(type==='RECEIVABLE'){await tx.account.update({where:{id:accountId},data:{balance:{decrement:amount}}}); }}}); revalidatePath('/debts'); revalidatePath('/dashboard');}
export async function payDebt(fd:FormData){const uid=await userId(); const debt=await prisma.debt.findFirst({where:{id:String(fd.get('debtId')),userId:uid}}); if(!debt)return; const amount=toNumber(fd.get('amount')); const accountId=debt.accountId||String(fd.get('accountId')||''); const date=new Date(String(fd.get('date'))); await assertOpen(uid,date); await prisma.$transaction(async tx=>{await tx.debtPayment.create({data:{userId:uid,debtId:debt.id,accountId,amount,date,notes:String(fd.get('notes')||'')}}); const remain=Number(debt.remainingAmount)-amount; await tx.debt.update({where:{id:debt.id},data:{remainingAmount:Math.max(0,remain),status:remain<=0?'PAID':'ACTIVE'}}); if(debt.type==='DEBT'){await tx.account.update({where:{id:accountId},data:{balance:{decrement:amount}}});}else{await tx.account.update({where:{id:accountId},data:{balance:{increment:amount}}}); } await tx.transaction.create({data:{userId:uid,accountId,type:debt.type==='DEBT'?'EXPENSE':'INCOME',amount,date,description:debt.type==='DEBT'?`Bayar hutang ${debt.name}`:`Terima piutang ${debt.name}`,sourceType:'debt_payment',sourceId:debt.id}});}); revalidatePath('/debts'); revalidatePath('/dashboard');}
export async function addInvestment(fd:FormData){const uid=await userId(); await prisma.investmentSnapshot.upsert({where:{userId_category_month:{userId:uid,category:String(fd.get('category')),month:String(fd.get('month'))}},create:{userId:uid,category:String(fd.get('category')),month:String(fd.get('month')),balance:toNumber(fd.get('balance')),notes:String(fd.get('notes')||'')},update:{balance:toNumber(fd.get('balance')),notes:String(fd.get('notes')||'')}}); revalidatePath('/investments'); revalidatePath('/dashboard');}
export async function addBill(fd:FormData){const uid=await userId(); await prisma.recurringBill.create({data:{userId:uid,accountId:String(fd.get('accountId')),name:String(fd.get('name')),amount:toNumber(fd.get('amount')),dueDay:Number(fd.get('dueDay')||1),notes:String(fd.get('notes')||'')}}); revalidatePath('/bills');}
export async function payBill(fd:FormData){const uid=await userId(); const bill=await prisma.recurringBill.findFirst({where:{id:String(fd.get('id')),userId:uid}}); if(!bill)return; const date=new Date(); await assertOpen(uid,date); await prisma.$transaction(async tx=>{await tx.recurringBill.update({where:{id:bill.id},data:{status:'PAID',lastPaidAt:date}}); await tx.account.update({where:{id:bill.accountId},data:{balance:{decrement:bill.amount}}}); await tx.transaction.create({data:{userId:uid,accountId:bill.accountId,type:'EXPENSE',amount:bill.amount,date,description:`Bayar tagihan ${bill.name}`,sourceType:'bill',sourceId:bill.id}});}); revalidatePath('/bills'); revalidatePath('/dashboard');}
export async function closeMonth(fd:FormData){const uid=await userId(); const month=String(fd.get('month')); const [accounts,transactions,cars,debts,investments]=await Promise.all([prisma.account.findMany({where:{userId:uid}}),prisma.transaction.findMany({where:{userId:uid,date:{gte:new Date(month+'-01'),lt:new Date(new Date(month+'-01').getFullYear(),new Date(month+'-01').getMonth()+1,1)}}}),prisma.car.findMany({where:{userId:uid,status:'AVAILABLE'}}),prisma.debt.findMany({where:{userId:uid,status:'ACTIVE'}}),prisma.investmentSnapshot.findMany({where:{userId:uid,month}})]); const income=transactions.filter(t=>t.type==='INCOME').reduce((a,t)=>a+Number(t.amount),0); const expense=transactions.filter(t=>t.type==='EXPENSE').reduce((a,t)=>a+Number(t.amount),0); const summary={income,expense,profit:income-expense,accounts:accounts.map(a=>({name:a.name,balance:String(a.balance)})),carAsset:cars.reduce((a,c)=>a+Number(c.estimatedSellPrice||c.purchasePrice),0),debt:debts.filter(d=>d.type==='DEBT').reduce((a,d)=>a+Number(d.remainingAmount),0),receivable:debts.filter(d=>d.type==='RECEIVABLE').reduce((a,d)=>a+Number(d.remainingAmount),0),investment:investments.reduce((a,i)=>a+Number(i.balance),0)}; await prisma.monthlyClosing.upsert({where:{userId_month:{userId:uid,month}},create:{userId:uid,month,summaryJson:summary},update:{summaryJson:summary}}); revalidatePath('/reports');}
